version: '3.8'
services:
  java-maven-app:
    image: manojpannala/java-maven-app:1.1.1-2
    ports:
      - 8080:8080
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD:my-pwd